// ==================== MUNICIPALITIES ====================

const municipalitiesByDistrict = {

    "Aveiro": [
        "Águeda",
        "Albergaria-a-Velha",
        "Anadia",
        "Arouca",
        "Aveiro",
        "Castelo de Paiva",
        "Espinho",
        "Estarreja",
        "Ílhavo",
        "Mealhada",
        "Murtosa",
        "Oliveira de Azeméis",
        "Oliveira do Bairro",
        "Ovar",
        "Santa Maria da Feira",
        "São João da Madeira",
        "Sever do Vouga",
        "Vagos",
        "Vale de Cambra"
    ],

    "Beja": [
        "Aljustrel",
        "Almodôvar",
        "Alvito",
        "Barrancos",
        "Beja",
        "Castro Verde",
        "Cuba",
        "Ferreira do Alentejo",
        "Mértola",
        "Moura",
        "Odemira",
        "Ourique",
        "Serpa",
        "Vidigueira"
    ],

    "Braga": [
        "Amares",
        "Barcelos",
        "Braga",
        "Cabeceiras de Basto",
        "Celorico de Basto",
        "Esposende",
        "Fafe",
        "Guimarães",
        "Póvoa de Lanhoso",
        "Terras de Bouro",
        "Vieira do Minho",
        "Vila Nova de Famalicão",
        "Vila Verde",
        "Vizela"
    ],

    "Bragança": [
        "Alfândega da Fé",
        "Bragança",
        "Carrazeda de Ansiães",
        "Freixo de Espada à Cinta",
        "Macedo de Cavaleiros",
        "Miranda do Douro",
        "Mirandela",
        "Mogadouro",
        "Torre de Moncorvo",
        "Vila Flor",
        "Vimioso",
        "Vinhais"
    ],

    "Castelo Branco": [
        "Belmonte",
        "Castelo Branco",
        "Covilhã",
        "Fundão",
        "Idanha-a-Nova",
        "Oleiros",
        "Penamacor",
        "Proença-a-Nova",
        "Sertã",
        "Vila de Rei",
        "Vila Velha de Ródão"
    ],

    "Coimbra": [
        "Arganil",
        "Cantanhede",
        "Coimbra",
        "Condeixa-a-Nova",
        "Figueira da Foz",
        "Góis",
        "Lousã",
        "Mira",
        "Miranda do Corvo",
        "Montemor-o-Velho",
        "Oliveira do Hospital",
        "Pampilhosa da Serra",
        "Penacova",
        "Penela",
        "Soure",
        "Tábua",
        "Vila Nova de Poiares"
    ],

    "Évora": [
        "Alandroal",
        "Arraiolos",
        "Borba",
        "Estremoz",
        "Évora",
        "Montemor-o-Novo",
        "Mora",
        "Mourão",
        "Portel",
        "Redondo",
        "Reguengos de Monsaraz",
        "Vendas Novas",
        "Viana do Alentejo",
        "Vila Viçosa"
    ],

    "Faro": [
        "Albufeira",
        "Alcoutim",
        "Aljezur",
        "Castro Marim",
        "Faro",
        "Lagoa",
        "Lagos",
        "Loulé",
        "Monchique",
        "Olhão",
        "Portimão",
        "São Brás de Alportel",
        "Silves",
        "Tavira",
        "Vila do Bispo",
        "Vila Real de Santo António"
    ],

    "Guarda": [
        "Aguiar da Beira",
        "Almeida",
        "Celorico da Beira",
        "Figueira de Castelo Rodrigo",
        "Fornos de Algodres",
        "Gouveia",
        "Guarda",
        "Manteigas",
        "Mêda",
        "Pinhel",
        "Sabugal",
        "Seia",
        "Trancoso",
        "Vila Nova de Foz Côa"
    ],

    "Leiria": [
        "Alcobaça",
        "Alvaiázere",
        "Ansião",
        "Batalha",
        "Bombarral",
        "Caldas da Rainha",
        "Castanheira de Pêra",
        "Figueiró dos Vinhos",
        "Leiria",
        "Marinha Grande",
        "Nazaré",
        "Óbidos",
        "Pedrógão Grande",
        "Peniche",
        "Pombal",
        "Porto de Mós"
    ],

    "Lisboa": [
        "Alenquer",
        "Amadora",
        "Arruda dos Vinhos",
        "Azambuja",
        "Cadaval",
        "Cascais",
        "Lisboa",
        "Loures",
        "Lourinhã",
        "Mafra",
        "Odivelas",
        "Oeiras",
        "Sintra",
        "Sobral de Monte Agraço",
        "Torres Vedras",
        "Vila Franca de Xira"
    ],

    "Portalegre": [
        "Alter do Chão",
        "Arronches",
        "Avis",
        "Campo Maior",
        "Castelo de Vide",
        "Crato",
        "Elvas",
        "Fronteira",
        "Gavião",
        "Marvão",
        "Monforte",
        "Nisa",
        "Ponte de Sor",
        "Portalegre",
        "Sousel"
    ],

    "Porto": [
        "Amarante",
        "Baião",
        "Felgueiras",
        "Gondomar",
        "Lousada",
        "Maia",
        "Marco de Canaveses",
        "Matosinhos",
        "Paços de Ferreira",
        "Paredes",
        "Penafiel",
        "Porto",
        "Póvoa de Varzim",
        "Santo Tirso",
        "Trofa",
        "Valongo",
        "Vila do Conde",
        "Vila Nova de Gaia"
    ],

    "Santarém": [
        "Abrantes",
        "Alcanena",
        "Almeirim",
        "Alpiarça",
        "Benavente",
        "Cartaxo",
        "Chamusca",
        "Constância",
        "Coruche",
        "Entroncamento",
        "Ferreira do Zêzere",
        "Golegã",
        "Mação",
        "Ourém",
        "Rio Maior",
        "Salvaterra de Magos",
        "Santarém",
        "Sardoal",
        "Tomar",
        "Torres Novas",
        "Vila Nova da Barquinha"
    ],

    "Setúbal": [
        "Alcácer do Sal",
        "Alcochete",
        "Almada",
        "Barreiro",
        "Grândola",
        "Moita",
        "Montijo",
        "Palmela",
        "Santiago do Cacém",
        "Seixal",
        "Sesimbra",
        "Setúbal",
        "Sines"
    ],

    "Viana do Castelo": [
        "Arcos de Valdevez",
        "Caminha",
        "Melgaço",
        "Monção",
        "Paredes de Coura",
        "Ponte da Barca",
        "Ponte de Lima",
        "Valença",
        "Viana do Castelo",
        "Vila Nova de Cerveira"
    ],

    "Vila Real": [
        "Alijó",
        "Boticas",
        "Chaves",
        "Mesão Frio",
        "Mondim de Basto",
        "Montalegre",
        "Murça",
        "Peso da Régua",
        "Ribeira de Pena",
        "Sabrosa",
        "Santa Marta de Penaguião",
        "Valpaços",
        "Vila Pouca de Aguiar",
        "Vila Real"
    ],

    "Viseu": [
        "Armamar",
        "Carregal do Sal",
        "Castro Daire",
        "Cinfães",
        "Lamego",
        "Mangualde",
        "Moimenta da Beira",
        "Mortágua",
        "Nelas",
        "Oliveira de Frades",
        "Penalva do Castelo",
        "Penedono",
        "Resende",
        "Santa Comba Dão",
        "São João da Pesqueira",
        "São Pedro do Sul",
        "Sátão",
        "Sernancelhe",
        "Tabuaço",
        "Tarouca",
        "Tondela",
        "Vila Nova de Paiva",
        "Viseu",
        "Vouzela"
    ],

    "Açores": [
        "Angra do Heroísmo",
        "Calheta",
        "Corvo",
        "Horta",
        "Lagoa",
        "Lajes das Flores",
        "Lajes do Pico",
        "Madalena",
        "Nordeste",
        "Ponta Delgada",
        "Povoação",
        "Praia da Vitória",
        "Ribeira Grande",
        "Santa Cruz da Graciosa",
        "Santa Cruz das Flores",
        "São Roque do Pico",
        "Velas",
        "Vila do Porto",
        "Vila Franca do Campo"
    ],

    "Madeira": [
        "Calheta",
        "Câmara de Lobos",
        "Funchal",
        "Machico",
        "Ponta do Sol",
        "Porto Moniz",
        "Porto Santo",
        "Ribeira Brava",
        "Santa Cruz",
        "Santana",
        "São Vicente"
    ]
};

// ==================== FIXED VALUE LISTS ====================

const stationStatuses = [
    "active",
    "under maintenance"
];

const chargeStatuses = [
    "in process",
    "terminated",
    "invoiced",
    "cancelled"
];

const chargeTypes = [
    "standard",
    "fast"
];

// ==================== PHONE PREFIXES ====================

const countryPrefixes = [
    { prefix: "+1", regex: /^\d{10}$/ },
    { prefix: "+7", regex: /^\d{10}$/ },
    { prefix: "+20", regex: /^\d{10}$/ },
    { prefix: "+27", regex: /^\d{9}$/ },
    { prefix: "+30", regex: /^\d{10}$/ },
    { prefix: "+31", regex: /^\d{9}$/ },
    { prefix: "+32", regex: /^\d{8,9}$/ },
    { prefix: "+33", regex: /^\d{9}$/ },
    { prefix: "+34", regex: /^\d{9}$/ },
    { prefix: "+36", regex: /^\d{9}$/ },
    { prefix: "+39", regex: /^\d{9,10}$/ },
    { prefix: "+40", regex: /^\d{9}$/ },
    { prefix: "+41", regex: /^\d{9}$/ },
    { prefix: "+43", regex: /^\d{4,13}$/ },
    { prefix: "+44", regex: /^\d{10}$/ },
    { prefix: "+45", regex: /^\d{8}$/ },
    { prefix: "+46", regex: /^\d{9}$/ },
    { prefix: "+47", regex: /^\d{8}$/ },
    { prefix: "+48", regex: /^\d{9}$/ },
    { prefix: "+49", regex: /^\d{5,11}$/ },
    { prefix: "+51", regex: /^\d{9}$/ },
    { prefix: "+52", regex: /^\d{10}$/ },
    { prefix: "+53", regex: /^\d{8}$/ },
    { prefix: "+54", regex: /^\d{10}$/ },
    { prefix: "+55", regex: /^\d{10,11}$/ },
    { prefix: "+56", regex: /^\d{9}$/ },
    { prefix: "+57", regex: /^\d{10}$/ },
    { prefix: "+58", regex: /^\d{10}$/ },
    { prefix: "+60", regex: /^\d{9,10}$/ },
    { prefix: "+61", regex: /^\d{9}$/ },
    { prefix: "+62", regex: /^\d{9,12}$/ },
    { prefix: "+63", regex: /^\d{10}$/ },
    { prefix: "+64", regex: /^\d{8,10}$/ },
    { prefix: "+65", regex: /^\d{8}$/ },
    { prefix: "+66", regex: /^\d{9}$/ },
    { prefix: "+81", regex: /^\d{9,10}$/ },
    { prefix: "+82", regex: /^\d{9,10}$/ },
    { prefix: "+84", regex: /^\d{9,10}$/ },
    { prefix: "+86", regex: /^\d{11}$/ },
    { prefix: "+90", regex: /^\d{10}$/ },
    { prefix: "+91", regex: /^\d{10}$/ },
    { prefix: "+92", regex: /^\d{10}$/ },
    { prefix: "+93", regex: /^\d{9}$/ },
    { prefix: "+94", regex: /^\d{9}$/ },
    { prefix: "+95", regex: /^\d{8,10}$/ },
    { prefix: "+98", regex: /^\d{10}$/ },

    { prefix: "+211", regex: /^\d{9}$/ },
    { prefix: "+212", regex: /^\d{9}$/ },
    { prefix: "+213", regex: /^\d{9}$/ },
    { prefix: "+216", regex: /^\d{8}$/ },
    { prefix: "+218", regex: /^\d{9}$/ },
    { prefix: "+220", regex: /^\d{7}$/ },
    { prefix: "+221", regex: /^\d{9}$/ },
    { prefix: "+222", regex: /^\d{8}$/ },
    { prefix: "+223", regex: /^\d{8}$/ },
    { prefix: "+224", regex: /^\d{9}$/ },
    { prefix: "+225", regex: /^\d{10}$/ },
    { prefix: "+226", regex: /^\d{8}$/ },
    { prefix: "+227", regex: /^\d{8}$/ },
    { prefix: "+228", regex: /^\d{8}$/ },
    { prefix: "+229", regex: /^\d{8}$/ },
    { prefix: "+230", regex: /^\d{8}$/ },
    { prefix: "+231", regex: /^\d{7,8}$/ },
    { prefix: "+232", regex: /^\d{8}$/ },
    { prefix: "+233", regex: /^\d{9}$/ },
    { prefix: "+234", regex: /^\d{10}$/ },
    { prefix: "+235", regex: /^\d{8}$/ },
    { prefix: "+236", regex: /^\d{8}$/ },
    { prefix: "+237", regex: /^\d{9}$/ },
    { prefix: "+238", regex: /^\d{7}$/ },
    { prefix: "+239", regex: /^\d{7}$/ },
    { prefix: "+240", regex: /^\d{9}$/ },
    { prefix: "+241", regex: /^\d{8}$/ },
    { prefix: "+242", regex: /^\d{9}$/ },
    { prefix: "+243", regex: /^\d{9}$/ },
    { prefix: "+244", regex: /^\d{9}$/ },
    { prefix: "+245", regex: /^\d{7}$/ },
    { prefix: "+248", regex: /^\d{7}$/ },
    { prefix: "+249", regex: /^\d{9}$/ },
    { prefix: "+250", regex: /^\d{9}$/ },
    { prefix: "+251", regex: /^\d{9}$/ },
    { prefix: "+252", regex: /^\d{8,9}$/ },
    { prefix: "+253", regex: /^\d{8}$/ },
    { prefix: "+254", regex: /^\d{9}$/ },
    { prefix: "+255", regex: /^\d{9}$/ },
    { prefix: "+256", regex: /^\d{9}$/ },
    { prefix: "+257", regex: /^\d{8}$/ },
    { prefix: "+258", regex: /^\d{9}$/ },
    { prefix: "+260", regex: /^\d{9}$/ },
    { prefix: "+261", regex: /^\d{9}$/ },
    { prefix: "+263", regex: /^\d{9}$/ },
    { prefix: "+264", regex: /^\d{9}$/ },
    { prefix: "+265", regex: /^\d{9}$/ },
    { prefix: "+266", regex: /^\d{8}$/ },
    { prefix: "+267", regex: /^\d{8}$/ },
    { prefix: "+268", regex: /^\d{8}$/ },
    { prefix: "+269", regex: /^\d{7}$/ },

    { prefix: "+290", regex: /^\d{4}$/ },
    { prefix: "+291", regex: /^\d{7}$/ },
    { prefix: "+297", regex: /^\d{7}$/ },
    { prefix: "+298", regex: /^\d{6}$/ },
    { prefix: "+299", regex: /^\d{6}$/ },

    { prefix: "+350", regex: /^\d{8}$/ },
    { prefix: "+351", regex: /^9\d{8}$/ },
    { prefix: "+352", regex: /^\d{9}$/ },
    { prefix: "+353", regex: /^\d{9}$/ },
    { prefix: "+354", regex: /^\d{7}$/ },
    { prefix: "+355", regex: /^\d{9}$/ },
    { prefix: "+356", regex: /^\d{8}$/ },
    { prefix: "+357", regex: /^\d{8}$/ },
    { prefix: "+358", regex: /^\d{9,10}$/ },
    { prefix: "+359", regex: /^\d{9}$/ },
    { prefix: "+370", regex: /^\d{8}$/ },
    { prefix: "+371", regex: /^\d{8}$/ },
    { prefix: "+372", regex: /^\d{7,8}$/ },
    { prefix: "+373", regex: /^\d{8}$/ },
    { prefix: "+374", regex: /^\d{8}$/ },
    { prefix: "+375", regex: /^\d{9}$/ },
    { prefix: "+376", regex: /^\d{6}$/ },
    { prefix: "+377", regex: /^\d{8,9}$/ },
    { prefix: "+378", regex: /^\d{10}$/ },
    { prefix: "+380", regex: /^\d{9}$/ },
    { prefix: "+381", regex: /^\d{8,9}$/ },
    { prefix: "+382", regex: /^\d{8}$/ },
    { prefix: "+383", regex: /^\d{8}$/ },
    { prefix: "+385", regex: /^\d{8,9}$/ },
    { prefix: "+386", regex: /^\d{8}$/ },
    { prefix: "+387", regex: /^\d{8}$/ },
    { prefix: "+389", regex: /^\d{8}$/ },

    { prefix: "+501", regex: /^\d{7}$/ },
    { prefix: "+502", regex: /^\d{8}$/ },
    { prefix: "+503", regex: /^\d{8}$/ },
    { prefix: "+504", regex: /^\d{8}$/ },
    { prefix: "+505", regex: /^\d{8}$/ },
    { prefix: "+506", regex: /^\d{8}$/ },
    { prefix: "+507", regex: /^\d{7,8}$/ },
    { prefix: "+509", regex: /^\d{8}$/ },

    { prefix: "+591", regex: /^\d{8}$/ },
    { prefix: "+592", regex: /^\d{7}$/ },
    { prefix: "+593", regex: /^\d{9}$/ },
    { prefix: "+594", regex: /^\d{9}$/ },
    { prefix: "+595", regex: /^\d{9}$/ },
    { prefix: "+597", regex: /^\d{7}$/ },
    { prefix: "+598", regex: /^\d{8}$/ },
    { prefix: "+599", regex: /^\d{7,8}$/ },

    { prefix: "+670", regex: /^\d{8}$/ },
    { prefix: "+672", regex: /^\d{6,8}$/ },
    { prefix: "+673", regex: /^\d{7}$/ },
    { prefix: "+674", regex: /^\d{7}$/ },
    { prefix: "+675", regex: /^\d{7}$/ },
    { prefix: "+676", regex: /^\d{7}$/ },
    { prefix: "+677", regex: /^\d{7}$/ },
    { prefix: "+678", regex: /^\d{7}$/ },
    { prefix: "+679", regex: /^\d{7}$/ },
    { prefix: "+680", regex: /^\d{7}$/ },
    { prefix: "+681", regex: /^\d{6}$/ },
    { prefix: "+682", regex: /^\d{5}$/ },
    { prefix: "+683", regex: /^\d{4}$/ },
    { prefix: "+685", regex: /^\d{7}$/ },
    { prefix: "+686", regex: /^\d{8}$/ },
    { prefix: "+687", regex: /^\d{6}$/ },
    { prefix: "+688", regex: /^\d{5,7}$/ },
    { prefix: "+689", regex: /^\d{8}$/ },
    { prefix: "+690", regex: /^\d{4}$/ },
    { prefix: "+691", regex: /^\d{7}$/ },
    { prefix: "+692", regex: /^\d{7}$/ },

    { prefix: "+850", regex: /^\d{8,10}$/ },
    { prefix: "+852", regex: /^\d{8}$/ },
    { prefix: "+853", regex: /^\d{8}$/ },
    { prefix: "+855", regex: /^\d{8,9}$/ },
    { prefix: "+856", regex: /^\d{8,10}$/ },
    { prefix: "+880", regex: /^\d{10}$/ },
    { prefix: "+886", regex: /^\d{9,10}$/ },

    { prefix: "+960", regex: /^\d{7}$/ },
    { prefix: "+961", regex: /^\d{7,8}$/ },
    { prefix: "+962", regex: /^\d{8,9}$/ },
    { prefix: "+963", regex: /^\d{9}$/ },
    { prefix: "+964", regex: /^\d{10}$/ },
    { prefix: "+965", regex: /^\d{8}$/ },
    { prefix: "+966", regex: /^\d{9}$/ },
    { prefix: "+967", regex: /^\d{9}$/ },
    { prefix: "+968", regex: /^\d{8}$/ },
    { prefix: "+970", regex: /^\d{9}$/ },
    { prefix: "+971", regex: /^\d{9}$/ },
    { prefix: "+972", regex: /^\d{9}$/ },
    { prefix: "+973", regex: /^\d{8}$/ },
    { prefix: "+974", regex: /^\d{8}$/ },
    { prefix: "+975", regex: /^\d{8}$/ },
    { prefix: "+976", regex: /^\d{8}$/ },
    { prefix: "+977", regex: /^\d{10}$/ },

    { prefix: "+992", regex: /^\d{9}$/ },
    { prefix: "+993", regex: /^\d{8}$/ },
    { prefix: "+994", regex: /^\d{9}$/ },
    { prefix: "+995", regex: /^\d{9}$/ },
    { prefix: "+996", regex: /^\d{9}$/ },
    { prefix: "+998", regex: /^\d{9}$/ }
];

// ==================== LICENCE PLATES ====================

const licencePlateFormats = [

    // ==================== AFRICA ====================

    { country: "Algeria", regex: /^\d{5}-\d{3}-\d{2}$/ },
    { country: "Angola", regex: /^(?:LD|LA|AO)-\d{2}-\d{2}-[A-Z]{2}$/ },
    { country: "Botswana", regex: /^[A-Z]{2}\s?\d{3}\s?[A-Z]$/ },
    { country: "Cameroon", regex: /^[A-Z]{2}\s?\d{4}\s?[A-Z]{2}$/ },
    { country: "Egypt", regex: /^[A-Z0-9]{1,8}$/ },
    { country: "Ghana", regex: /^[A-Z]{2}\s?\d{4}-\d{2}$/ },
    { country: "Kenya", regex: /^[A-Z]{3}\s?\d{3}[A-Z]$/ },
    { country: "Morocco", regex: /^\d{1,5}\s?[A-Z]{1,2}\s?\d{1,2}$/ },
    { country: "Mozambique", regex: /^[A-Z]{2,3}-\d{2}-\d{2}$/ },
    { country: "Namibia", regex: /^[A-Z]{2}\s?\d{4}$/ },
    { country: "Nigeria", regex: /^[A-Z]{3}\s?\d{3}[A-Z]{2}$/ },
    { country: "Rwanda", regex: /^(?:R[A-Z]{2}\s?\d{3}[A-Z])$/ },
    { country: "Senegal", regex: /^[A-Z]{2}\s?\d{4}\s?[A-Z]{2}$/ },
    { country: "South Africa", regex: /^[A-Z]{2}\s?\d{3}\s?[A-Z]{2}$/ },
    { country: "Tanzania", regex: /^[A-Z]{2,3}\s?\d{3}[A-Z]{1,2}$/ },
    { country: "Tunisia", regex: /^\d{3}\s?\d{4}$/ },
    { country: "Uganda", regex: /^[U][A-Z]{2}\s?\d{3}[A-Z]$/ },
    { country: "Zambia", regex: /^[A-Z]{3}\s?\d{4}$/ },
    { country: "Zimbabwe", regex: /^[A-Z]{2,3}\s?\d{4}$/ },

    // ==================== ASIA ====================

    { country: "Afghanistan", regex: /^[A-Z]{1,3}\s?\d{1,5}$/ },
    { country: "Bangladesh", regex: /^[A-Z]{2}\s?\d{2}-\d{4}$/ },
    { country: "Bhutan", regex: /^[A-Z]{2}-\d{4}$/ },
    { country: "Brunei", regex: /^[A-Z]{1,2}\s?\d{4}$/ },
    { country: "Cambodia", regex: /^[A-Z]{1,2}\s?\d{4}$/ },
    { country: "China", regex: /^[A-Z]\s?[A-Z0-9]{5}$/ },
    { country: "India", regex: /^[A-Z]{2}\s?\d{1,2}\s?[A-Z]{1,3}\s?\d{1,4}$/ },
    { country: "Indonesia", regex: /^[A-Z]{1,2}\s?\d{1,4}\s?[A-Z]{1,3}$/ },
    { country: "Iran", regex: /^\d{2}\s?[A-Z]\s?\d{3}\s?\d{2}$/ },
    { country: "Iraq", regex: /^[A-Z]{1,3}\s?\d{1,6}$/ },
    { country: "Israel", regex: /^\d{2,3}-\d{2,3}-\d{2,3}$/ },
    { country: "Japan", regex: /^\d{2,3}-\d{2}\s?[A-Z0-9]{1,2}\s?\d{2}$/ },
    { country: "Jordan", regex: /^[A-Z]{1,3}\s?\d{1,5}$/ },
    { country: "Kazakhstan", regex: /^\d{3}[A-Z]{3}\s?\d{2}$/ },
    { country: "Kuwait", regex: /^\d{1,5}$/ },
    { country: "Laos", regex: /^[A-Z]{2}\s?\d{4}$/ },
    { country: "Lebanon", regex: /^\d{6}$/ },
    { country: "Malaysia", regex: /^[A-Z]{1,3}\s?\d{1,4}$/ },
    { country: "Mongolia", regex: /^[A-Z]{1,3}\s?\d{4}$/ },
    { country: "Myanmar", regex: /^[A-Z]{2,3}\s?\d{4}$/ },
    { country: "Nepal", regex: /^[A-Z]{2}\s?\d{1,4}$/ },
    { country: "Oman", regex: /^[A-Z]{1,2}\s?\d{1,5}$/ },
    { country: "Pakistan", regex: /^[A-Z]{2,3}\s?\d{1,4}$/ },
    { country: "Philippines", regex: /^[A-Z]{3}\s?\d{4}$/ },
    { country: "Qatar", regex: /^[A-Z]{1,2}\s?\d{4,5}$/ },
    { country: "Saudi Arabia", regex: /^\d{4}\s?[A-Z]{3}$/ },
    { country: "Singapore", regex: /^[A-Z]{1,3}\s?\d{1,4}[A-Z]$/ },
    { country: "South Korea", regex: /^\d{2,3}[A-Z]\s?\d{4}$/ },
    { country: "Sri Lanka", regex: /^[A-Z]{2}\s?\d{4}$/ },
    { country: "Taiwan", regex: /^[A-Z]{2,3}-\d{4,5}$/ },
    { country: "Thailand", regex: /^[A-Z]{2}\s?\d{1,4}$/ },
    { country: "United Arab Emirates", regex: /^[A-Z0-9]{1,6}$/ },
    { country: "Uzbekistan", regex: /^\d{1,2}\s?[A-Z]\s?\d{3}[A-Z]{2}$/ },
    { country: "Vietnam", regex: /^\d{2}[A-Z]-\d{3}\.\d{2}$/ },

    // ==================== EUROPE ====================

    { country: "Albania", regex: /^[A-Z]{2}\s?\d{3}\s?[A-Z]{2}$/ },
    { country: "Andorra", regex: /^[A-Z]{1,2}\d{4}$/ },
    { country: "Austria", regex: /^[A-Z]{1,2}-[A-Z]{1,2}\s?\d{1,5}$/ },
    { country: "Belgium", regex: /^[A-Z]-?\d{3}-?\d{3}$/ },
    { country: "Bosnia and Herzegovina", regex: /^[A-Z]{1,2}\s?\d{3,4}-[A-Z]{1,2}$/ },
    { country: "Bulgaria", regex: /^[A-Z]{1,2}\s?\d{4}\s?[A-Z]{1,2}$/ },
    { country: "Croatia", regex: /^[A-Z]{2}\s?\d{3,4}-[A-Z]{1,2}$/ },
    { country: "Cyprus", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Czech Republic", regex: /^[A-Z]\d{1,2}\s?\d{4,5}$/ },
    { country: "Denmark", regex: /^[A-Z]{2}\s?\d{1,5}$/ },
    { country: "Estonia", regex: /^\d{3}[A-Z]{3}$/ },
    { country: "Finland", regex: /^[A-Z]{3}-\d{3}$/ },
    { country: "France", regex: /^[A-Z]{2}-\d{3}-[A-Z]{2}$/ },
    { country: "Germany", regex: /^[A-Z]{1,3}(?:-[A-Z]{1,2})?\s?\d{1,4}$/ },
    { country: "Greece", regex: /^[A-Z]{3}-\d{4}$/ },
    { country: "Hungary", regex: /^[A-Z]{3}-[A-Z]{3}\s?\d{3}$/ },
    { country: "Iceland", regex: /^[A-Z]{2}\s?\d{3,4}$/ },
    { country: "Ireland", regex: /^\d{2,3}-[A-Z]{1,2}-\d{1,6}$/ },
    { country: "Italy", regex: /^[A-Z]{2}\s?\d{3}\s?[A-Z]{2}$/ },
    { country: "Latvia", regex: /^[A-Z]{2}-\d{1,4}$/ },
    { country: "Liechtenstein", regex: /^[FL]\s?\d{1,5}$/ },
    { country: "Lithuania", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Luxembourg", regex: /^[A-Z]{2}\s?\d{4}$/ },
    { country: "Malta", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Moldova", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Monaco", regex: /^\d{4}\s?[A-Z]$/ },
    { country: "Montenegro", regex: /^[A-Z]{2}\s?\d{3,4}-[A-Z]{1,2}$/ },
    { country: "Netherlands", regex: /^[A-Z0-9]{2,3}-[A-Z0-9]{2,3}-[A-Z0-9]{2,3}$/ },
    { country: "North Macedonia", regex: /^[A-Z]{2}\s?\d{4}-[A-Z]{2}$/ },
    { country: "Norway", regex: /^[A-Z]{2}\s?\d{5}$/ },
    { country: "Poland", regex: /^[A-Z]{1,3}\s?[A-Z0-9]{4,5}$/ },
    {
        country: "Portugal",
        regex: /^(?:[A-Z]{2}-\d{2}-[A-Z]{2}|\d{2}-[A-Z]{2}-\d{2}|\d{2}-\d{2}-[A-Z]{2}|[A-Z]{2}-\d{2}-\d{2})$/
    },
    { country: "Romania", regex: /^[A-Z]{1,2}\s?\d{2,3}\s?[A-Z]{3}$/ },
    { country: "San Marino", regex: /^[A-Z]{1,2}\s?\d{4}$/ },
    { country: "Serbia", regex: /^[A-Z]{2}\s?\d{3,4}-[A-Z]{2}$/ },
    { country: "Slovakia", regex: /^[A-Z]{2}\s?\d{3}[A-Z]{2}$/ },
    { country: "Slovenia", regex: /^[A-Z]{2}\s?\d{3,4}$/ },
    { country: "Spain", regex: /^\d{4}\s?[A-Z]{3}$/ },
    { country: "Sweden", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Switzerland", regex: /^[A-Z]{1,2}\s?\d{1,6}$/ },
    { country: "Turkey", regex: /^\d{2}\s?[A-Z]{1,3}\s?\d{2,5}$/ },
    { country: "Ukraine", regex: /^[A-Z]{2}\s?\d{4}\s?[A-Z]{2}$/ },
    { country: "United Kingdom", regex: /^[A-Z]{2}\d{2}\s?[A-Z]{3}$/ },

    // ==================== NORTH AMERICA ====================

    { country: "Canada", regex: /^[A-Z0-9]{2,8}$/ },
    { country: "Costa Rica", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Cuba", regex: /^[A-Z]\s?\d{5}$/ },
    { country: "Dominican Republic", regex: /^[A-Z0-9]{2,7}$/ },
    { country: "El Salvador", regex: /^[A-Z]{1,3}-\d{4}$/ },
    { country: "Guatemala", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Honduras", regex: /^[A-Z]{3}\s?\d{3,4}$/ },
    { country: "Jamaica", regex: /^[A-Z]{2,3}\s?\d{4}$/ },
    { country: "Mexico", regex: /^[A-Z0-9]{2,8}$/ },
    { country: "Nicaragua", regex: /^[A-Z]{1,3}\s?\d{4}$/ },
    { country: "Panama", regex: /^[A-Z]{2,3}\s?\d{4}$/ },
    { country: "United States", regex: /^[A-Z0-9]{1,8}$/ },

    // ==================== OCEANIA ====================

    { country: "Australia", regex: /^[A-Z0-9]{2,7}$/ },
    { country: "Fiji", regex: /^[A-Z]{2}\s?\d{3}$/ },
    { country: "New Zealand", regex: /^[A-Z]{1,3}\s?\d{1,4}$/ },
    { country: "Papua New Guinea", regex: /^[A-Z]{2}\s?\d{4}$/ },
    { country: "Samoa", regex: /^[A-Z]{2}\s?\d{3}$/ },
    { country: "Tonga", regex: /^[A-Z]{1,2}\s?\d{3,4}$/ },

    // ==================== SOUTH AMERICA ====================

    { country: "Argentina", regex: /^[A-Z]{2}\s?\d{3}\s?[A-Z]{2}$/ },
    { country: "Bolivia", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Brazil", regex: /^[A-Z]{3}-\d[A-Z0-9]\d{2}$/ },
    { country: "Chile", regex: /^[A-Z]{2}\s?\d{2}\s?\d{2}$/ },
    { country: "Colombia", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Ecuador", regex: /^[A-Z]{3}-\d{3,4}$/ },
    { country: "Paraguay", regex: /^[A-Z]{3}\s?\d{3}$/ },
    { country: "Peru", regex: /^[A-Z]{3}-\d{3}$/ },
    { country: "Uruguay", regex: /^[A-Z]{3}\s?\d{3,4}$/ },
    { country: "Venezuela", regex: /^[A-Z]{3}\s?\d{3}$/ }
];

// ==================== STATIONS ====================

const stations = [
    {
        id: 1,
        code: "S001",
        district: "Braga",
        municipality: "Braga",
        standardPower: 20,
        fastPower: 100,
        connectorType: "MJG",
        status: "active",
        lastMaintenance: "2026-08-26T16:00"
    },
    {
        id: 2,
        code: "S002",
        district: "Porto",
        municipality: "Porto",
        standardPower: 20,
        fastPower: 100,
        connectorType: "DSG",
        status: "under maintenance",
        lastMaintenance: "2026-08-10T09:00"
    },
    {
        id: 3,
        code: "S003",
        district: "Coimbra",
        municipality: "Coimbra",
        standardPower: 20,
        fastPower: 100,
        connectorType: "MJG",
        status: "active",
        lastMaintenance: "2026-08-02T11:00"
    },
    {
        id: 4,
        code: "S004",
        district: "Lisboa",
        municipality: "Lisboa",
        standardPower: 20,
        fastPower: 100,
        connectorType: "MGS",
        status: "active",
        lastMaintenance: "2026-08-20T14:00"
    }
];

const inactiveStations = [];

// ==================== CLIENTS ====================

const clients = [
    {
        id: 1,
        tif: "271747390",
        firstName: "Pedro",
        lastName: "Gomes",
        dob: "1995-07-13",
        phoneNumber: "+351916291322",
        licenceCountry: "Portugal",
        licencePlate: "AA-21-BB",
        points: 7
    },
    {
        id: 2,
        tif: "278934321",
        firstName: "Maria",
        lastName: "Silva",
        dob: "1998-01-15",
        phoneNumber: "+351915439865",
        licenceCountry: "Portugal",
        licencePlate: "GH-45-AC",
        points: 0
    },
];

const inactiveClients = [];

// ==================== TARIFFS ====================

const tariffs = [
    {
        id: 1,
        name: "Normal",
        chargeType: "standard",
        pricePerKwh: 0.35,
        activationFee: 0.50,
    },
    {
        id: 2,
        name: "Premium",
        chargeType: "fast",
        pricePerKwh: 0.65,
        activationFee: 1.00,
    },
];

const inactiveTariffs = [];

// ==================== CHARGES ====================

const charges = [
    {
        id: 1,
        stationCode: "S001",
        clientId: 1,
        startDate: "2026-07-15T16:00",
        endDate: "2026-07-15T17:00",
        duration: 1,
        energy: 20,
        tariffId: 1,
        cost: 7.50,
        status: "invoiced",
    },
    {
        id: 2,
        stationCode: "S003",
        clientId: 1,
        startDate: "2026-03-26T12:00",
        endDate: "2026-03-26T12:00",
        duration: 0,
        energy: 0,
        tariffId: 1,
        cost: 0,
        status: "cancelled",
    },
    {
        id: 3,
        stationCode: "S002",
        clientId: 2,
        startDate: "2026-01-12T10:00",
        endDate: "2026-01-12T11:00",
        duration: 1,
        energy: 100,
        tariffId: 2,
        cost: 66.00,
        status: "terminated",
    },
    {
        id: 4,
        stationCode: "S003",
        clientId: 2,
        startDate: "2026-08-12T14:00",
        endDate: null,
        duration: null,
        energy: null,
        tariffId: 2,
        cost: null,
        status: "in process",
    },
];

const inactiveCharges = [];

// ==================== MAINTENANCE CONSTANT ====================

const maintenanceInterval = 15 * 24 * 60 * 60 * 1000;

module.exports = {
    municipalitiesByDistrict,
    stationStatuses,
    chargeStatuses,
    chargeTypes,
    countryPrefixes,
    licencePlateFormats,
    stations,
    inactiveStations,
    clients,
    inactiveClients,
    tariffs,
    inactiveTariffs,
    charges,
    inactiveCharges,
    maintenanceInterval
};